import {useState} from 'react';
import {motion,useMotionValue,useReducedMotion,useSpring,useTransform} from 'motion/react';
import {ArrowDownRight,ArrowUpRight,CaretDown,Check,Play,Sparkle,X} from '@phosphor-icons/react';
const A=`${import.meta.env.BASE_URL}assets/`;
const gallery=['1bb4a3fc59c86dc4.jpg','5ef017e4626965f7.jpg','b9b7e62ff7d5633d.jpg','98ae41cb44393170.jpg','eb8c8a80c1529ce9.jpg'];
const benefits=[['Готовое изделие','Сплетёте первую работу вместе с Полиной прямо на эфире.'],['3 полезных подарка','Инструкции и уроки останутся у вас после мастер-класса.'],['Творческая перезагрузка','Два часа спокойной работы руками вместо повседневной суеты.'],['План развития','Поймёте, как превратить новое хобби в дополнительный доход.']];
const faq=[['Нужно ли что-то приготовить?','После регистрации вы получите короткий список доступных материалов.'],['Сколько длится мастер-класс?','Около двух часов. Этого хватит, чтобы познакомиться с техникой и сделать первую работу.'],['Я никогда не плела. Мне подойдёт?','Да. Полина показывает каждый шаг крупно и объясняет без сложных терминов.'],['Как записаться?','Выберите удобное время и нажмите кнопку регистрации. Ссылка придёт после записи.']];
function MagneticButton({children,light=false,...props}){const reduce=useReducedMotion(),x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:180,damping:16}),sy=useSpring(y,{stiffness:180,damping:16});return <motion.button {...props} className={`magnetic ${light?'light':''}`} style={reduce?{}:{x:sx,y:sy}} onMouseMove={e=>{if(reduce)return;const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.18);y.set((e.clientY-r.top-r.height/2)*.22)}} onMouseLeave={()=>{x.set(0);y.set(0)}} whileTap={{scale:.96}}>{children}<ArrowDownRight weight="bold"/></motion.button>}
function Tilt({children,className=''}){const reduce=useReducedMotion(),px=useMotionValue(.5),py=useMotionValue(.5),rx=useTransform(py,[0,1],[7,-7]),ry=useTransform(px,[0,1],[-7,7]);return <motion.div className={className} style={reduce?{}:{rotateX:rx,rotateY:ry,transformPerspective:900}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();px.set((e.clientX-r.left)/r.width);py.set((e.clientY-r.top)/r.height)}} onMouseLeave={()=>{px.set(.5);py.set(.5)}}>{children}</motion.div>}
function Reveal({children,className=''}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:38}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.75,ease:[.16,1,.3,1]}}>{children}</motion.div>}
function Signup({compact=false}){const[open,setOpen]=useState(false);return <><div className={`signup-actions ${compact?'compact':''}`}><button onClick={()=>setOpen(true)}><span>11:00</span> Записаться</button><button onClick={()=>setOpen(true)}><span>19:00</span> Записаться</button></div>{open&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} onClick={()=>setOpen(false)}><motion.div className="modal" initial={{scale:.9,y:24}} animate={{scale:1,y:0}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOpen(false)} aria-label="Закрыть"><X/></button><span className="kicker">11 августа 2026</span><h3>Ваше место почти готово</h3><p>Выберите время, оставьте контакты и получите материалы для подготовки.</p><label>Имя<input placeholder="Как к вам обращаться"/></label><label>Телефон<input placeholder="+7 999 000-00-00"/></label><MagneticButton>Забронировать</MagneticButton></motion.div></motion.div>}</>}
export default function App(){const[menu,setMenu]=useState(false);return <main><header className="nav"><a className="logo" href="#top">плету<br/>лозу</a><nav>{['Что узнаете','Для кого','Об авторе','Отзывы'].map((x,i)=><a key={x} href={['#program','#for-whom','#author','#reviews'][i]}>{x}</a>)}</nav><button className="nav-cta" onClick={()=>document.querySelector('#register').scrollIntoView({behavior:'smooth'})}>Записаться <ArrowUpRight/></button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<span>меню</span>}</button></header>{menu&&<div className="mobile-menu">{['Что узнаете','Для кого','Об авторе','Отзывы'].map((x,i)=><a onClick={()=>setMenu(false)} key={x} href={['#program','#for-whom','#author','#reviews'][i]}>{x}</a>)}</div>}
<section className="hero" id="top"><div className="hero-copy"><motion.span className="kicker" initial={{opacity:0}} animate={{opacity:1}}>Бесплатный мастер-класс</motion.span><motion.h1 initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:.8}}>Плетите <em>красоту</em></motion.h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.15}}>Создайте декор как из Pinterest своими руками всего за 2 часа. Подходит даже новичкам.</motion.p><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.3}}><MagneticButton onClick={()=>document.querySelector('#register').scrollIntoView({behavior:'smooth'})}>Выбрать время</MagneticButton></motion.div></div><div className="hero-media"><motion.div className="sun" animate={{rotate:360}} transition={{duration:28,repeat:Infinity,ease:'linear'}}><Sparkle weight="fill"/></motion.div><Tilt className="hero-photo"><img src={A+'1bb4a3fc59c86dc4.jpg'} alt="Плетёная корзина ручной работы"/><div className="price"><small>участие</small><b>0 ₽</b><s>1990 ₽</s></div></Tilt><motion.div className="orbit" animate={{rotate:-360}} transition={{duration:16,repeat:Infinity,ease:'linear'}}>БУМАЖНАЯ ЛОЗА • СВОИМИ РУКАМИ •</motion.div></div></section>
<section className="date-band" id="register"><div><span>Ближайший эфир</span><strong>11 августа 2026</strong></div><Signup compact/></section>
<section className="gifts" id="program"><Reveal className="section-head"><span className="kicker">Подарки за регистрацию</span><h2>Начните плести<br/>ещё до эфира</h2><p>Сразу после регистрации откроем материалы, которые помогут подготовиться и почувствовать технику руками.</p></Reveal><div className="gift-grid"><Tilt className="gift gift-one"><div className="gift-video"><video src={A+'91a42c543ffc7b3c.mp4'} autoPlay muted loop playsInline/></div><span>Видео-урок</span><h3>Плетёное сердце «Валентинка»</h3><Play weight="fill"/></Tilt><Tilt className="gift gift-two"><span>Практическая инструкция</span><h3>Изготовление и обработка бумажной лозы</h3><img src={A+'5ef017e4626965f7.jpg'} alt="Кресло из бумажной лозы"/><Check weight="bold"/></Tilt></div></section>
<section className="benefits" id="for-whom"><Reveal><span className="kicker">Что вы получите</span><h2>Результат, который можно потрогать</h2></Reveal><div className="benefit-list">{benefits.map((b,i)=><motion.article key={b[0]} whileHover={{x:12}}><span>0{i+1}</span><h3>{b[0]}</h3><p>{b[1]}</p><ArrowUpRight/></motion.article>)}</div></section>
<section className="gallery"><div className="marquee"><div>ПЛЕТЕНИЕ УСПОКАИВАЕТ • РУКИ ПОМНЯТ • КРАСОТА ОСТАЁТСЯ • ПЛЕТЕНИЕ УСПОКАИВАЕТ • РУКИ ПОМНЯТ • КРАСОТА ОСТАЁТСЯ •</div></div><div className="gallery-track">{gallery.map((im,i)=><motion.figure key={im} whileHover={{scale:1.035,rotate:i%2?1.5:-1.5}}><img src={A+im} alt="Работа ученицы школы плетения"/></motion.figure>)}</div></section>
<section className="author" id="author"><div className="author-media"><video src={A+'af084575ba78b143.mp4'} autoPlay muted loop playsInline/></div><Reveal className="author-copy"><span className="kicker">Полина Майорова</span><h2>Научу видеть материал и не бояться первой петли</h2><p>Автор школы «Плету лозу». Полина объясняет технику спокойно, точно и с уважением к вашему темпу.</p><div className="facts"><div><b>с нуля</b><span>до первой работы</span></div><div><b>2 часа</b><span>живой практики</span></div></div><MagneticButton light>Познакомиться</MagneticButton></Reveal></section>
<section className="reviews" id="reviews"><Reveal><span className="kicker">Отзывы учениц</span><h2>«Теперь я могу плести сама»</h2></Reveal><div className="review-grid"><article><p>«Впервые встречаю такой ответственный подход и настолько качественное обучение. Настоящая школа плетения.»</p><span>Наталия</span></article><article><p>«Корзинами я бредила лет пятнадцать. Теперь дарю свои работы близким и не верю, что сделала их сама.»</p><span>Вероника</span></article><article className="review-photo"><img src={A+'b55edb0124837a2e.webp'} alt="Плетёное кресло ученицы"/></article></div></section>
<section className="faq"><Reveal><span className="kicker">Вопросы</span><h2>Всё просто. Даже если вы начинаете с нуля</h2></Reveal><div className="accordion">{faq.map(([q,a])=><details key={q}><summary>{q}<CaretDown/></summary><p>{a}</p></details>)}</div></section>
<section className="final"><div className="final-bg"><img src={A+'5ef017e4626965f7.jpg'} alt="Интерьер с плетёным креслом"/></div><Reveal className="final-copy"><span className="kicker">Давайте творить вместе</span><h2>Ваши руки уже умеют больше, чем вы думаете</h2><p>Выберите удобное время и приходите на бесплатный мастер-класс 11 августа.</p><Signup/></Reveal></section>
<footer><a className="logo" href="#top">плету<br/>лозу</a><p>ИП Майорова Полина Вадимовна<br/>ИНН 771472141040</p><div><a href="https://online.pletulozu.ru/dogovor_oferta">Договор оферты</a><a href="https://online.pletulozu.ru/politika">Политика данных</a></div><span>© 2026</span></footer></main>}
